management:
    endpoints:
        web:
            exposure:
                include: health,info
server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
        context-path: /server-storage
        register-default-servlet: true
spring:
    application:
        name: storage
    aop:
        auto: false
        proxy-target-class: true
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
            # 需要使用 kafka 时注释掉让其能自动配置
            - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
    cloud:
        nacos:
            server-addr: https://test.youshengyun.com:443
            username: nacos
            password: ${NACOS_PASSWORD:111111}
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: test
            discovery:
                enabled: false
                group: DEFAULT_GROUP
                namespace: test
    config:
        import:
            - optional:nacos:storage.yml
            #- optional:nacos:test01.yml?group=group_02
            #- optional:nacos:test02.yml?group=group_03&refreshEnabled=false
    data:
        redis:
            database: 8
            host: localhost
            port: 6379
            username: default
            password: '111111'
            ssl:
                enabled: false
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 8
                    max-wait: -1
                    min-idle: 1
            repositories:
                enabled: false
    datasource:
        hikari:
            y9-public:
                driverClassName: com.mysql.cj.jdbc.Driver
                jdbcUrl: jdbc:mysql://localhost:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: '111111'
                maximumPoolSize: 20
                minimumIdle: 1
    jpa:
        #databasePlatform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: none
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: none
                jdbc:
                    batchSize: 100
                showSql: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9storage-server
    main:
        allow-bean-definition-overriding: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    servlet:
        multipart:
            max-file-size: 2048MB
            max-request-size: 2048MB
y9:
    systemName: storage
    internalIp: 192.168.x.x,10.x.x.x,172.20.x.x
    app:
        storage:
            #单次上传限制/字节 120Mb
            singleUploadLimit: 125829120
            #默认存储容量/字节
            defaultStorageCapacity: 5368709120
            fileManagerSystemName: itemAdmin
            publicManagerRoleName: 公共文件管理角色
            capacityManagerRoleName: 存储空间管理角色
            reportManagerRoleName: 文件上报管理角色
            productDocument: 95b19opvx9d40458c002dd61c41eb2c
    service:
        org:
            directUrl: http://localhost:7055
    common:
        kafkaEnabled: false
        orgBaseUrl: http://127.0.0.1:7055/server-platform
        jodconverterBaseUrl: https://www.youshengyun.com/jodconverter/onlinePreview?url=
        storageBaseUrl: http://localhost:7058/server-storage
        logBaseUrl: http://localhost:7056/server-log
        userOnlineBaseUrl: http://localhost:7056/server-useronline
    feature:
        file:
            base64FileName: false
            encryptionFileContent: false
            #privateKey:
            #publicKey:
            rest:
                fileManagerUrl: http://localhost:8080/filemanager
            ftp:
                host: localhost
                port: 21
                username: y9admin
                password: '111111'
                blockWhenExhausted: true
                bufferSize: 10240
                connectTimeOut: 50000
                controlEncoding: UTF-8
                dataTimeout: 1200000
                fileType: 2
                maxIdle: 10
                maxTotal: 50
                minIdle: 2
                maxWaitMillis: 5400000
                testOnBorrow: true
                testOnCreate: true
                testOnReturn: true
                testWhileIdle: true
                useEPSVwithIPv4: false
                passiveMode: true
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
        liquibase:
            tenant-enabled: true
        multi-tenant:
            # kafka, db
            event-source: db
        log:
            enabled: true
            # kafka, api
            reportMethod: api
        session:
            redis:
                enabled: true
                maxInactiveIntervalInSeconds: 3600
        security:
            enabled: true
            csrf:
                accepted-referer:
                    - youshengyun.com
                    - localhost
                    - 127.0.0.1
            cors:
                allowCredentials: true
                allowed-headers: '*'
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - http://localhost:7055
                    - http://localhost:7056
                    - http://localhost:7058
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://localhost:8082
                    - http://localhost:8083
                    - http://localhost:8084
                    - http://127.0.0.1:7055
                    - http://127.0.0.1:7056
        oauth2:
            resource:
                enabled: true
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /vue/*
                opaque:
                    client-id: clientid_oidc
                    client-secret: secret_oidc
                    introspection-uri: http://localhost:7055/sso/oidc/introspect
                    profile-uri: http://localhost:7055/sso/oidc/profile
