server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
        context-path: /dataAssets
        register-default-servlet: true
spring:
    application:
        name: dataAssets
    aop:
        auto: false
        proxy-target-class: true
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
            # 需要使用 kafka 时注释掉让其能自动配置
            - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
    cloud:
        nacos:
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: dev
                server-addr: https://dev.youshengyun.com:443
                username: nacos
                password: ${NACOS_PASSWORD:111111}
            discovery:
                enabled: false
    config:
        import:
            - optional:nacos:dataAssets.yml
            #- optional:nacos:test01.yml?group=group_02
            #- optional:nacos:test02.yml?group=group_03&refreshEnabled=false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 2000
                wall:
                    config:
                        drop-table-allow: false
                    enabled: true
            stat-view-servlet:
                allow: 10.168.18.1/24,10.168.12.1/24
                enabled: false
                login-password: '83204585'
                login-username: y9admin
                reset-enable: false
                url-pattern: /druid/*
            web-stat-filter:
                enabled: true
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/static/*'
                url-pattern: /*
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            y9-public:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_kernal?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false
                username: root
                #driver-class-name: oracle.jdbc.OracleDriver
                #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
                #username: Y9_PUBLIC
                password: 111111
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                cache:
                    use_query_cache: false
                    use_second_level_cache: false
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: update
                jdbc:
                    batch_size: 100
                show_sql: false
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9dataAssets-server
    main:
        allow-bean-definition-overriding: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    servlet:
        multipart:
            max-file-size: 2048MB
            max-request-size: 2048MB
    redis:
        database: 8
        host: 127.0.0.1
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
            shutdown-timeout: 100ms
        password: y9i-83204585
        port: 6379
        ssl: false
        timeout: 10000
y9:
    systemName: dataAssets
    internalIp: 192.168.x.x,10.0.x.x,172.20.x.x
    app:
        dataAssets:
            fileManagerSystemName: itemAdmin
            managerRoleName: 管理员角色
            productDocument: 95b19opvx9d40458c002dd61c41eb2c
            upload-folder: D:\testPlaceholder\upload
            tenantId: c425281829dc4d4496ddddf7fc0198d0
    service:
        org:
            directUrl: https://test-api.youshengyun.com
    common:
        kafkaEnabled: false
        orgBaseUrl: http://127.0.0.1:7055/platform
        jodconverterBaseUrl: https://www.youshengyun.com/jodconverter/onlinePreview?url=
        dataAssetsBaseUrl: http://localhost:7056/dataAssets
        logBaseUrl: http://localhost:7056/log
        userOnlineBaseUrl: http://localhost:7056/userOnline
    feature:
        file:
            base64FileName: false
            encryptionFileContent: false
            #privateKey: 
            #publicKey: 
            ftp:
                enabled: false
                host: localhost
                port: 21
                username: y9admin
                password: '111111'
                blockWhenExhausted: true
                bufferSize: 10240
                connectTimeOut: 50000
                controlEncoding: UTF-8
                dataTimeout: 1200000
                fileType: 2
                maxIdle: 10
                maxTotal: 50
                minIdle: 2
                maxWaitMillis: 5400000
                testOnBorrow: true
                testOnCreate: true
                testOnReturn: true
                testWhileIdle: true
                useEPSVwithIPv4: false
                passiveMode: true
            local:
                enabled: true
                # 本地文件存储的根路径，按需设置为自己的
                basePath: "d:/y9FileStore"
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
        liquibase:
            tenant-enabled: false
        log:
            enabled: false
            # kafka, api
            logSaveTarget: kafka
        session:
            redis:
                enabled: true
                maxInactiveIntervalInSeconds: 3600
        security:
            enabled: true
            cors:
                allowCredentials: true
                allowed-headers: '*'
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - http://localhost:7055
                    - http://localhost:7056
                    - http://localhost:7058
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://localhost:8082
                    - http://localhost:8083
                    - http://localhost:8084
                    - http://127.0.0.1:7055
                    - http://127.0.0.1:7056
                    - http//192.168.3.218:7056
                    - http//192.168.3.171:7056
            xss:
                ignoreParam:
                    - tables
                    - fields
                    - idAndIsShowJson
                    - formDataJson
                    - rulesJson
            csrf:
                acceptedReferer:
                    - 127.0.0.1
                    - localhost
                    - demo.youshengyun.com
                    - test.youshengyun.com
                    - test-api.youshengyun.com
        oauth2:
            resource:
                enabled: true
                saveOnlineMessage: false
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /vue/*
                opaque:
                    client-id: clientid
                    client-secret: secret
                    introspection-uri: https://test.youshengyun.com/sso/oauth2.0/introspect
                    profile-uri: https://test.youshengyun.com/sso/oauth2.0/profile
idCode:
    #统一码接口地址
    idCode_url: https://api.idcode.org.cn
    #统一码解析地址
    analyze_url: http://s.idcode.org.cn/
    #单位主码
    main_code: MA.156.1003.1629
    #系统授权key
    api_key: 9XRMKN90QA8O90SDAAAAAKJ
    #系统授权码
    api_code: 09DN09QA8X08XRNN9DRMXRXM9DNAK09Q
    #统一码解析地址
    goto_url: https://test.youshengyun.com/data-assets/goto
    #统一码示例地址
    sample_url: https://test.youshengyun.com/data-assets/goto
