management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    intranet:
        ip: 192.168.x.x,10.168.x.x
    port: 7055
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
spring:
    application:
        name: storage
    aop:
        auto: false
        proxy-target-class: true
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    cloud:
        nacos:
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: dev
                server-addr: https://dev.youshengyun.com:443
                username: nacos
                password: nacos@2022
            discovery:
                enabled: false
    config:
        import:
            - optional:nacos:storage.yml
            #- optional:nacos:test01.yml?group=group_02
            #- optional:nacos:test02.yml?group=group_03&refreshEnabled=false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 2000
                wall:
                    config:
                        drop-table-allow: false
                    enabled: true
            stat-view-servlet:
                allow: 10.168.18.1/24,10.168.12.1/24
                enabled: true
                login-password: '83204585'
                login-username: y9admin
                reset-enable: false
                url-pattern: /druid/*
            web-stat-filter:
                enabled: true
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/static/*'
                url-pattern: /*
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            y9-public:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_public_new?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false
                username: root
                #driver-class-name: oracle.jdbc.OracleDriver
                #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
                #username: Y9_PUBLIC
                password: 111111
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                cache:
                    use_query_cache: false
                    use_second_level_cache: false
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: none
                jdbc:
                    batch_size: 100
                show_sql: true
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9storage-server
    main:
        allow-bean-definition-overriding: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    servlet:
        multipart:
            max-file-size: 2048MB
            max-request-size: 2048MB
    redis:
        database: 8
        host: 127.0.0.1
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
            shutdown-timeout: 100ms
        password: y9i-83204585
        port: 6379
        ssl: false
        timeout: 10000
y9:
    systemName: storage
    app:
        storage:
            #单次上传限制/字节 120Mb
            singleUploadLimit: 125829120
            #默认存储容量/字节
            defaultStorageCapacity: 5368709120
            fileManagerSystemName: itemAdmin
            publicManagerRoleName: 公共文件管理角色
            capacityManagerRoleName: 存储空间管理角色
            reportManagerRoleName: 文件上报管理角色
            productDocument: 95b19opvx9d40458c002dd61c41eb2c
    service:
        org:
            directUrl: http://localhost:7055
    common:
        kafkaEnabled: true
        orgBaseUrl: http://127.0.0.1:7055/platform
        jodconverterBaseUrl: https://www.youshengyun.com/jodconverter/onlinePreview?url=
        storageBaseUrl: http://localhost:7058/storage
        logBaseUrl: http://localhost:7056/log
        userOnlineBaseUrl: http://localhost:7056/userOnline
    feature:
        file:
            base64FileName: false
            encryptionFileContent: false
            #privateKey: 
            #publicKey: 
            rest:
                fileManagerUrl: http://localhost:8080/fileManager
            ftp:
                host: localhost
                port: 21
                username: y9admin
                password: '111111'
                blockWhenExhausted: true
                bufferSize: 10240
                connectTimeOut: 50000
                controlEncoding: UTF-8
                dataTimeout: 1200000
                fileType: 2
                maxIdle: 10
                maxTotal: 50
                minIdle: 2
                maxWaitMillis: 5400000
                testOnBorrow: true
                testOnCreate: true
                testOnReturn: true
                testWhileIdle: true
                useEPSVwithIPv4: false
                passiveMode: true
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
        
        license:
            publicKey: "30820122300d06092a864886f70d01010105000382010f00303032301006072a8648ce3d02002EC311215SHA512withECDSA106052b81040006031e0004766422ea9a7afb8dae15b491c6ef1e591d9d4bfc992437f82f8a480bG82010a02820101008675a892587630b07efbb4a55d20190348f8ce88b42c311362a4527c6cf0774233b77ef2a50084d3338c76ada1c9039d6935d4bfb635312f5a0d6a700bb2c41745f29bb7ed4f9712fba324bb68cfed5cb38556a7782b795b1243c64a03RSA4204813SHA512withRSA649e6772e14983d65ae7b3bae9fef7f8ff47443e545d4917808946b9a1bdbaf1d8378951f4cfae5c49377b7e92ee7aac300cd204d0f5c0766c8a9800f4f2fb6232c93b68c68c867d1bfe013e2b81f3497f9de02eee384f97cc704800c6a0d32684592ce08087d8619626493ceb1308d61c26a81e703af6a5abffce0d56f11e24dc48b9aaf1277b7181c35bc537fabf47ef756102a14964728ee2b9462cfff4d7a7ed5ddd0203010001"
            internalString: risesoft-youshengyun-y9
            hardwareIdMethod: 0
            productId: risesoft-y9
            productEdition: test
            productVersion: 9.4.0
            licenseFileOnDisk: https://vue.youshengyun.com/license/y9license.lic
            licenseString: '7e78efc812dada5c29668827783dbee481319d160e7d231bb84f4ad0752ed1e6f794fb15c741021f6a6a42a4ab49541511a775647223a7daf0a5f3b113d38eb2f6972b9b35fe5eace335ace6bdf3729bb63eb672898afd7f5c95f283d6e4eb864b3134fdeafdac826f429482d7d8d190542c55eb245f9e706f996c97d0e825745807aa5c432b1ba7426f1a28086df098ed782cc52204bb92d4290bbaf883f26e774eb2e7b355a1eab6ffadc0b2cac2db3d4ace0c04257a9af51534a6009b7512e12fa27c01b48473a10bcd3d38a992d5c4b5c17e5903695cb742204a716544c69a7ad12614e92d0560fff3c2a8e7004083df92e19b78ff2d5a917f16cabe24f448c765b597901ec65dba2dfea36214b971c7f69b11ecdbb37814c8b0ab92b4c3b7f98c197198b35aa8e5eca1dffebbdae134997ff892dfca010447846d9ca7969c483627f6f3f0436564678b59a01b867f1357479588f22296bcb3c14b8f707d5188b3e90b334ecdb04c250108a56ac35f0578a652dd31786dd066dd8fa35c2ca4fc1602765d68cd7e8c8a1818391479ba549dd9241c4b47482f6b6c3066061908aa20114ba87c0db9291703b608d0cf297a2b711f6ec47b4ac79cc54cb5bb6fb62c8fc9309a2f48cf9f1fe84ff6c4402556e0374786e557ab65602b40e3f8531f4fa5fe960b7d62bd2c2a6bb9ca59eefe19c22f2d852e52cb74ada38faa2d024c360df3d65810d6d6ea346da0c2f676e261d294e9b833d971a14954f062c996609e1b5cd374824854690fb22e1254e97c48c5641647345988b11f22fe6ce128572413c0a5e1080168c7b6524c26b83953981b02065a21ae877186890c0791d6e1cc20bd6e081429e2c9a106c383c4fe44bb3b9037a29cf8178c24959bc4be523250829d9eed870439470da0949d3ac7d52d9a1653595cb0fa2f53a894da7fc08831487d75174c53b41d284652859333'
        liquibase:
            tenant-enabled: true
        log:
            enabled: true
            # kafka, api
            logSaveTarget: kafka
        session:
            redis:
                enabled: true
                maxInactiveIntervalInSeconds: 3600
        security:
            enabled: true
            cors:
                allowCredentials: true
                allowed-headers: '*'
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - http://localhost:7055
                    - http://localhost:7056
                    - http://localhost:7058
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://localhost:8082
                    - http://localhost:8083
                    - http://localhost:8084
                    - http://127.0.0.1:7055
                    - http://127.0.0.1:7056
        oauth2:
            resource:
                enabled: true
                saveLogMessage: false
                saveOnlineMessage: false
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /vue/*
                opaque:
                    client-id: clientid
                    client-secret: secret
                    introspection-uri: http://localhost:7055/sso/oauth2.0/introspect
                    profile-uri: http://localhost:7055/sso/oauth2.0/profile
